In [3]:
import torch


n1, n2 = torch.randn(8), torch.randn(8)
n1, n2

(tensor([ 0.3533, -0.8894, -0.0984, -0.2390, -0.4550, -1.6379, -1.9510, -0.9513]),
 tensor([ 1.2332,  0.7049,  0.4769,  0.5771,  0.4895, -0.0055, -2.0285,  0.8295]))

In [5]:
torch.nn.functional.log_softmax(n1)

/tmp/ipykernel_1002142/942364214.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.log_softmax(n1)


tensor([-1.2330, -2.4757, -1.6847, -1.8253, -2.0412, -3.2242, -3.5373, -2.5376])

In [8]:
torch.nn.functional.kl_div(torch.nn.functional.log_softmax(n1), torch.nn.functional.softmax(n2))

/tmp/ipykernel_1002142/1303133214.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.kl_div(torch.nn.functional.log_softmax(n1), torch.nn.functional.softmax(n2))
/tmp/ipykernel_1002142/1303133214.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.kl_div(torch.nn.functional.log_softmax(n1), torch.nn.functional.softmax(n2))


tensor(0.0120)