In [1]:
import sys
sys.path.append('../')

import starry.utils.env

In [2]:
from starry.paraff.midiseq import T2I


with open('../../intelli-piano/footages/40318-p0.spartito.midiseq.txt') as file:
	segments = file.readlines()
	segments = [[T2I[token] for token in segment.strip().split(' ')] for segment in segments]

segments

[[311,
  40,
  40,
  204,
  128,
  35,
  204,
  123,
  28,
  204,
  116,
  35,
  204,
  128,
  123,
  40,
  40,
  204,
  128,
  35,
  204,
  123,
  28,
  204,
  116,
  35,
  204,
  128,
  123],
 [311,
  44,
  40,
  40,
  204,
  128,
  35,
  204,
  123,
  28,
  204,
  116,
  35,
  204,
  132,
  128,
  123,
  47,
  44,
  40,
  40,
  204,
  128,
  35,
  204,
  123,
  28,
  204,
  116,
  35,
  204,
  135,
  132,
  128,
  123],
 [311,
  49,
  44,
  40,
  40,
  204,
  128,
  35,
  204,
  137,
  123,
  47,
  28,
  204,
  116,
  35,
  204,
  132,
  135,
  128,
  123,
  44,
  46,
  40,
  40,
  204,
  128,
  37,
  204,
  125,
  28,
  204,
  116,
  37,
  204,
  128,
  125],
 [311,
  40,
  40,
  204,
  128,
  37,
  204,
  125,
  28,
  204,
  116,
  37,
  204,
  47,
  132,
  134,
  128,
  125,
  47,
  44,
  40,
  40,
  204,
  128,
  35,
  204,
  135,
  49,
  135,
  123,
  49,
  28,
  204,
  137,
  47,
  137,
  116,
  47,
  35,
  204,
  135,
  132,
  135,
  128,
  123],
 [311,
  46,
  46,
  44,
  40

In [3]:
import os

from starry.utils.model_factory import loadModel
from starry.utils.config import Configuration


TRAINING_DIR = os.environ.get('TRAINING_DIR')

config = Configuration.createOrLoad(os.path.join(TRAINING_DIR, 'paraff/20241130-midiseq-paraff-se-ly+cc-d256-l8-dw0.06'))
model = loadModel(config['model'], postfix='JitEnc')
model

/home/camus/work/deep-starry/env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-12-03 18:45:07.840032: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-03 18:45:07.840073: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-03 18:45:07.841351: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-03 18:45:07.848725: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow b

SeqShareSEJitEnc(
  (word_emb): Embedding(324, 256, padding_idx=0)
  (word_prj): Linear(in_features=256, out_features=324, bias=False)
  (latent_prj): Linear(in_features=256, out_features=256, bias=False)
  (latent_emb): Linear(in_features=256, out_features=256, bias=True)
  (position_enc): PositionalEncoding()
  (layer_norm): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
  (attention): AttentionStack(
    (layer_stack): ModuleList(
      (0-7): 8 x EncoderLayer(
        (slf_attn): MultiHeadAttention(
          (w_qs): Linear(in_features=256, out_features=256, bias=False)
          (w_ks): Linear(in_features=256, out_features=256, bias=False)
          (w_vs): Linear(in_features=256, out_features=256, bias=False)
          (fc): Linear(in_features=256, out_features=256, bias=False)
          (attention): ScaledDotProductAttention(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (dropout): Dropout(p=0.1, inplace=False)
          (layer_norm): LayerNor

In [4]:
import torch


checkpoint = torch.load(config.localPath(config['best']), map_location='cpu')
checkpoint

/tmp/ipykernel_2821893/28622449.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(config.localPath(config['best']), map_location='cpu')


{'epoch': 3405,
 'model': OrderedDict([('word_emb.weight',
               tensor([[-0.3351,  0.4023,  0.6013,  ..., -0.2226, -0.1850,  0.1750],
                       [-0.4882,  1.9941,  0.6937,  ..., -0.0584, -0.0276,  0.0616],
                       [-0.0877,  0.0390,  0.9322,  ..., -0.0627, -0.0261,  0.0215],
                       ...,
                       [-0.3348,  0.4025,  0.6014,  ..., -0.2225, -0.1848,  0.1751],
                       [-0.3341,  0.4032,  0.6019,  ..., -0.2222, -0.1843,  0.1755],
                       [-0.3345,  0.4029,  0.6017,  ..., -0.2224, -0.1846,  0.1753]])),
              ('word_prj.weight',
               tensor([[-0.3351,  0.4023,  0.6013,  ..., -0.2226, -0.1850,  0.1750],
                       [-0.4882,  1.9941,  0.6937,  ..., -0.0584, -0.0276,  0.0616],
                       [-0.0877,  0.0390,  0.9322,  ..., -0.0627, -0.0261,  0.0215],
                       ...,
                       [-0.3348,  0.4025,  0.6014,  ..., -0.2225, -0.1848,  0.1751]

In [5]:
model.load_state_dict(checkpoint['model'], strict=False)

<All keys matched successfully>

In [6]:
input = torch.tensor([2] + segments[0] + [3]).long()[None]
input

tensor([[  2, 311,  40,  40, 204, 128,  35, 204, 123,  28, 204, 116,  35, 204,
         128, 123,  40,  40, 204, 128,  35, 204, 123,  28, 204, 116,  35, 204,
         128, 123,   3]])

In [7]:
model.eval()

SeqShareSEJitEnc(
  (word_emb): Embedding(324, 256, padding_idx=0)
  (word_prj): Linear(in_features=256, out_features=324, bias=False)
  (latent_prj): Linear(in_features=256, out_features=256, bias=False)
  (latent_emb): Linear(in_features=256, out_features=256, bias=True)
  (position_enc): PositionalEncoding()
  (layer_norm): LayerNorm((256,), eps=1e-06, elementwise_affine=True)
  (attention): AttentionStack(
    (layer_stack): ModuleList(
      (0-7): 8 x EncoderLayer(
        (slf_attn): MultiHeadAttention(
          (w_qs): Linear(in_features=256, out_features=256, bias=False)
          (w_ks): Linear(in_features=256, out_features=256, bias=False)
          (w_vs): Linear(in_features=256, out_features=256, bias=False)
          (fc): Linear(in_features=256, out_features=256, bias=False)
          (attention): ScaledDotProductAttention(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (dropout): Dropout(p=0.1, inplace=False)
          (layer_norm): LayerNor

In [8]:
with torch.no_grad():
	out = model(input)

out.shape

torch.Size([1, 256])