In [1]:
import sys
import os


sys.path.append('..')
os.chdir('..')

In [ ]:
# load original model
import os
import torch

from starry.utils.config import Configuration
from starry.utils.dataset_factory import loadDataset
from starry.utils.model_factory import loadModel


torch.set_printoptions(profile="full")

DATA_DIR = os.getenv('DATA_DIR')

config = Configuration.create('./configs/paraff-visionund-test.yaml', volatile=True)
train, = loadDataset(config, data_dir=DATA_DIR, splits='*0/1', device='cuda')
model = loadModel(config['model'], postfix='Loss').cuda()

it = iter(train)
batch = next(it)
batch['input_ids']

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
2025-03-18 11:09:39.160791: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-18 11:09:39.160831: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 11:09:39

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

tensor([[100000,   2054,    418,    245,   9394,   4706,    285,  10046,  20308,
             13,   1257,    418,   2249,    276,   2579,    254,   7959,   3093,
            344,    254,   2677,   4614,     11,    285,   4750,    254,   2677,
            366,    245,   6265,    280,   9224,   1244,   3892,   4706,     13,
            185,    185, 100601,     25,    207, 100016, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100

In [1]:
# load trained model
import os
import torch

from starry.utils.config import Configuration
from starry.utils.dataset_factory import loadDataset
from starry.utils.model_factory import loadModel


torch.set_printoptions(profile="full")

DATA_DIR = os.getenv('DATA_DIR')

config = Configuration(os.path.expanduser('/root/training/p/deepslog/paraff/20250321-paraff-visionund-janus-ly0226-l15-ae/'), volatile=True)
train, = loadDataset(config, data_dir=DATA_DIR, splits='*0/1', device='cuda')
model = loadModel(config['model'], postfix='Loss').cuda()

checkpoint = torch.load(config.localPath('latest.chkpt'), map_location='cuda')
model.deducer.load_state_dict(checkpoint['model'])

model.eval()

it = iter(train)
batch = next(it)
batch['input_ids']

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.


Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

tensor([[100000,   2054,    418,    207,     64,   9394,   4706,    285,  10046,
          20308,     13,   1257,    418,   2249,    276,   2579,    254,   7959,
           3093,    344,    254,   2677,   4614,     11,    285,   4750,    254,
           2677,    366,    207,     64,   6265,    280,   9224,   1244,   3892,
           4706,     13,    185,    185, 100601,     25,    207, 100016, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100

In [2]:
prompt_len = batch['target_mask'][0].tolist().index(True)
prompt_len

635

In [3]:
input_ids = batch['input_ids'][:, :prompt_len]
input_ids

tensor([[100000,   2054,    418,    207,     64,   9394,   4706,    285,  10046,
          20308,     13,   1257,    418,   2249,    276,   2579,    254,   7959,
           3093,    344,    254,   2677,   4614,     11,    285,   4750,    254,
           2677,    366,    207,     64,   6265,    280,   9224,   1244,   3892,
           4706,     13,    185,    185, 100601,     25,    207, 100016, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100

In [18]:
from transformers import AutoTokenizer


tokenizer = AutoTokenizer.from_pretrained("/root/training/jp7")

input_text = tokenizer.decode(input_ids[0])
input_text

'<｜begin▁of▁sentence｜>You are a helpful language and vision assistant. You are able to understand the visual content that the user provides, and assist the user with a variety of tasks using natural language.\n\n<|User|>: <begin_of_image><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><i

In [19]:
img_emb = model.aligner(batch['img_emb'][:1].to(model.dtype))
img_emb.shape

torch.Size([1, 1, 576, 4096])

In [20]:
inputs_embeds = model.deducer.embed_input(input_ids[:1])
image_seq_mask = batch['image_seq_mask']
img_emb = img_emb.reshape((-1, img_emb.shape[-1]))
inputs_embeds[image_seq_mask[:1, :prompt_len]] = img_emb
inputs_embeds.shape

torch.Size([1, 635, 4096])

In [25]:
outputs = model.deducer.janus.generate(
    inputs_embeds=inputs_embeds,
    attention_mask=batch['attention_mask'][:1, :prompt_len],
    pad_token_id=tokenizer.eos_token_id,
    bos_token_id=tokenizer.bos_token_id,
    eos_token_id=tokenizer.eos_token_id,
    max_new_tokens=256,
    do_sample=False,
    use_cache=True,
    temperature=0,
    top_p=1,
)

outputs

tensor([[   207, 100605,    207, 100618,    207, 100627,    207, 100637,    207,
         100607,    207, 100610,    207,  82708,    207,     64,    207, 100640,
            207, 100640,    207,     69,    207, 100649,    207, 100681,    207,
             68,    207, 100649,    207,     67,    207, 100649,    207, 100649,
            207,     68,    207, 100640,    207,     69,    207, 100650,    207,
         100649,    207,  11153,    207,  46718,    207, 100608,    207, 100610,
            207,  82708,    207,     64,    207, 100640,    207, 100646,    207,
             69,    207, 100640,    207,     64,    207, 100649,    207, 100681,
            207,     69,    207, 100641,    207,     64,    207, 100649,    207,
         100649,    207,     64,    207, 100640,    207,     69,    207, 100640,
            207,     64,    207, 100640,    207, 100648,    207,  11153,    207,
          46718,    207, 100608,    207,  47008,    207,     64,    207, 100646,
            207, 100654,    

In [26]:
tokenizer.decode(outputs[0])

' BOM K_1 TN4 TD4 S1 Cg Md a Osup Osup f D16 EslurL e D16 d D16 D16 e Osup f D32 D16 Br VB S2 Cg Md a Osup D2 f Osup a D16 EslurL f Osub a D16 D16 a Osup f Osup a Osup D8 Br VB S2 Cf a D2 RSpace f Osub a Osub D8 f Osub a Osup D8 Br EOM f Osub a Osup D16 f Osup a Osup D16 Br EOM EOM f Osup a Osup D16 f Osup a Osup D8 Br EOM EOM f Osup a Osup D16 f Osup a Osup D8 Br EOM EOM EOM f Osup a Osup D16 f Osup a Osup D8 Br EOM EOM f Osup a Osup D8 Br Osup VB'

In [27]:
target_ids = batch['input_ids'][:, prompt_len:]
target_ids

tensor([[   207, 100605,    207, 100618,    207, 100627,    207, 100637,    207,
         100607,    207, 100610,    207,  82708,    207,     70,    207, 100640,
            207, 100640,    207, 100640,    207, 100649,    207,   7643,    207,
             69,    207, 100649,    207,     67,    207, 100649,    207,     65,
            207,  27841,    207, 100649,    207,  11153,    207,     70,    207,
         100649,    207,   7643,    207,     69,    207, 100649,    207,     67,
            207, 100649,    207,     65,    207,  27841,    207, 100649,    207,
          11153,    207,     66,    207, 100649,    207,   7643,    207,     69,
            207, 100649,    207,     70,    207, 100649,    207,     64,    207,
         100649,    207,  11153,    207, 100643,    207, 100643,    207,     66,
            207, 100649,    207,   7643,    207,     69,    207, 100649,    207,
             70,    207, 100649,    207,     64,    207, 100649,    207,  11153,
            207,  46718,    

In [28]:
target_text = tokenizer.decode(target_ids[0])
target_text

' BOM K_1 TN4 TD4 S1 Cg Md g Osup Osup Osup D16 Bl f D16 d D16 b Af D16 Br g D16 Bl f D16 d D16 b Af D16 Br c D16 Bl f D16 g D16 a D16 Br Ova Ova c D16 Bl f D16 g D16 a D16 Br VB S2 Cf Md f Osub b Af d f D2 Eac f a c f D4 f a c f D4 EOM<｜end▁of▁sentence｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜><｜▁pad▁｜>'