In [1]:
import sys
import os


sys.path.append('..')
os.chdir('..')

In [ ]:
# load original model
import os
import torch

from starry.utils.config import Configuration
from starry.utils.dataset_factory import loadDataset
from starry.utils.model_factory import loadModel


torch.set_printoptions(profile="full")

DATA_DIR = os.getenv('DATA_DIR')

config = Configuration.create('./configs/paraff-visionund-test.yaml', volatile=True)
train, = loadDataset(config, data_dir=DATA_DIR, splits='*0/1', device='cuda')
model = loadModel(config['model'], postfix='Loss').cuda()

it = iter(train)
batch = next(it)
batch['input_ids']

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
2025-03-18 11:09:39.160791: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-18 11:09:39.160831: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 11:09:39

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

tensor([[100000,   2054,    418,    245,   9394,   4706,    285,  10046,  20308,
             13,   1257,    418,   2249,    276,   2579,    254,   7959,   3093,
            344,    254,   2677,   4614,     11,    285,   4750,    254,   2677,
            366,    245,   6265,    280,   9224,   1244,   3892,   4706,     13,
            185,    185, 100601,     25,    207, 100016, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100

In [2]:
# load trained model
import os
import torch

from starry.utils.config import Configuration
from starry.utils.dataset_factory import loadDataset
from starry.utils.model_factory import loadModel


torch.set_printoptions(profile="full")

DATA_DIR = os.getenv('DATA_DIR')

config = Configuration(os.path.expanduser('~/data/training/paraff/20250317-paraff-visionund-test/'), volatile=True)
train, = loadDataset(config, data_dir=DATA_DIR, splits='*0/1', device='cuda')
model = loadModel(config['model'], postfix='Loss').cuda()

checkpoint = torch.load(config.localPath('latest.chkpt'), map_location='cuda')
model.deducer.load_state_dict(checkpoint['model'])

model.eval()

it = iter(train)
batch = next(it)
batch['input_ids']

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
2025-03-18 14:36:01.551445: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-18 14:36:01.551481: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-18 14:36:01

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

/tmp/ipykernel_264975/2784088976.py:18: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(config.localPath('latest.chkpt'), map_location='cuda')


tensor([[100000,   2054,    418,    245,   9394,   4706,    285,  10046,  20308,
             13,   1257,    418,   2249,    276,   2579,    254,   7959,   3093,
            344,    254,   2677,   4614,     11,    285,   4750,    254,   2677,
            366,    245,   6265,    280,   9224,   1244,   3892,   4706,     13,
            185,    185, 100601,     25,    207, 100016, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100

In [3]:
prompt_len = batch['target_mask'][0].tolist().index(True)
prompt_len

632

In [4]:
input_ids = batch['input_ids'][:, :prompt_len]
input_ids

tensor([[100000,   2054,    418,    245,   9394,   4706,    285,  10046,  20308,
             13,   1257,    418,   2249,    276,   2579,    254,   7959,   3093,
            344,    254,   2677,   4614,     11,    285,   4750,    254,   2677,
            366,    245,   6265,    280,   9224,   1244,   3892,   4706,     13,
            185,    185, 100601,     25,    207, 100016, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594, 100594,
         100594, 100594, 100

In [5]:
from transformers import AutoTokenizer


tokenizer = AutoTokenizer.from_pretrained("deepseek-ai/Janus-Pro-7B")

input_text = tokenizer.decode(input_ids[0])
input_text

'<｜begin▁of▁sentence｜>You are a helpful language and vision assistant. You are able to understand the visual content that the user provides, and assist the user with a variety of tasks using natural language.\n\n<|User|>: <begin_of_image><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><image_placeholder><i

In [6]:
img_emb = model.aligner(batch['img_emb'].to(model.dtype))
img_emb.shape

torch.Size([1, 1, 576, 4096])

In [7]:
inputs_embeds = model.deducer.get_input_embeddings()(input_ids)
image_seq_mask = batch['image_seq_mask']
img_emb = img_emb.reshape((-1, img_emb.shape[-1]))
inputs_embeds[image_seq_mask[:, :prompt_len]] = img_emb

inputs_embeds.shape

torch.Size([1, 632, 4096])

In [8]:
outputs = model.deducer.generate(
    inputs_embeds=inputs_embeds,
    attention_mask=batch['attention_mask'][:, :prompt_len],
    pad_token_id=tokenizer.eos_token_id,
    bos_token_id=tokenizer.bos_token_id,
    eos_token_id=tokenizer.eos_token_id,
    max_new_tokens=64,
    do_sample=False,
    use_cache=True,
    temperature=0,
    top_p=1,
)

outputs

/home/camus/work/deep-starry/env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:590: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(


tensor([[  1733,    245,    414,     17,    427,   3847,    332,     49,  55570,
            324,     16,    339,     70,  14680,    258,    508,   3683,    414,
             17,    427,   3847,    332,     43,  78703,    307,    508,   3683,
            414,     17,    427,   3847,    332,     49,    307,    414,     17,
            427,   3847,    332,     43,    307,    414,     17,    427,   3847,
            332,     49,    307,    414,     17,    427,   3847,    332,     43,
            307,    414,     17,    427,   3847,    332,     49,    427,   3681,
         100001]], device='cuda:0')

In [9]:
tokenizer.decode(outputs[0])

' As a D2 EslurR VB S1 Cg Mu c Osup D2 EslurL Md g Osup D2 EslurR g D2 EslurL g D2 EslurR g D2 EslurL g D2 EslurR EOM<｜end▁of▁sentence｜>'

In [10]:
target_ids = batch['input_ids'][:, prompt_len:]
target_ids

tensor([[    33,   3681,    721,     16,  41746,     18,  36963,     19,    324,
             16,    339,     70,    270,    508,   3683,    414,     17,  38484,
          14757,  55570,    324,     16,    339,     70,  78703,    245,    508,
           3683,    414,     23,   2799,    267,   1733,    414,     23,    245,
            414,     23,    301,    414,     23,    263,   1733,    414,     23,
            270,    508,   3683,    414,     23,   3069,  55570,    324,     17,
          45031,    301,    508,   1588,    414,     17,  38484,  14757,    427,
           3681, 100001]], device='cuda:0')

In [11]:
target_text = tokenizer.decode(target_ids[0])
target_text

'BOM K1 TN3 TD4 S1 Cg b Osup D2 Dot Rest VB S1 Cg Md a Osup D8 Bl f As D8 a D8 e D8 d As D8 b Osup D8 Br VB S2 Cf e Osub D2 Dot Rest EOM<｜end▁of▁sentence｜>'